project:
  type: website

website:
  title: "Hirotaka Fukui"
  site-url: https://fukui-hirotaka.com/
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
       -href: notes.qmd
        text: Notes

page-footer:
    right: "&copy; 2025 Hirotaka Fukui. All rights reserved."


format:
  html:
    theme:
      - quartz
      - brand
    css: styles.css
    toc: true
    smooth-scroll: true


