project:
  type: website
  output-dir: docs

website:
  title: "Hirotaka Fukui"
  favicon: images/logo.jpg
  navbar:
    logo: images/logo.jpg
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact

page-footer:
    right: "&copy; 2025 Hirotaka Fukui. All rights reserved."


format:
  html:
    theme:
      - quartz
      - brand
    css: styles.css
    toc: true
    smooth-scroll: true
    code-copy: true



